export const BODY_ART: Record<string, string> = {
  sun: "/bodies/sun.png",
  mercury: "/bodies/mercury.png",
  venus: "/bodies/venus.png",
  earth: "/bodies/earth.png",
  mars: "/bodies/mars.png",
  jupiter: "/bodies/jupiter.png",
  saturn: "/bodies/saturn.png",
  uranus: "/bodies/uranus.png",
  neptune: "/bodies/neptune.png",
  moon: "/bodies/moon.png",
  phobos: "/bodies/phobos.png",
  deimos: "/bodies/deimos.png",
  io: "/bodies/io.png",
  europa: "/bodies/europa.png",
  ganymede: "/bodies/ganymede.png",
  callisto: "/bodies/callisto.png",
  mimas: "/bodies/mimas.png",
  enceladus: "/bodies/enceladus.png",
  tethys: "/bodies/tethys.png",
  dione: "/bodies/dione.png",
  rhea: "/bodies/rhea.png",
  titan: "/bodies/titan.png",
  iapetus: "/bodies/iapetus.png",
  miranda: "/bodies/miranda.png",
  ariel: "/bodies/ariel.png",
  umbriel: "/bodies/umbriel.png",
  titania: "/bodies/titania.png",
  oberon: "/bodies/oberon.png",
  triton: "/bodies/triton.png",
};

export const MOON_ART_IDS = [
  "moon",
  "phobos",
  "deimos",
  "io",
  "europa",
  "ganymede",
  "callisto",
  "mimas",
  "enceladus",
  "tethys",
  "dione",
  "rhea",
  "titan",
  "iapetus",
  "miranda",
  "ariel",
  "umbriel",
  "titania",
  "oberon",
  "triton",
] as const;
