type BodyEntry = {
  id: string;
  name: string;
  type: "dwarf-planet" | "asteroid" | "comet" | "region" | "moon";
  parentId: string | null;
  au: number;
  innerAu?: number;
  localOrbit?: number;
  longitudeDeg: number;
  displaySize: number;
  color: string;
  hardOnly?: boolean;
  difficulty?: number;
};

function body(partial: BodyEntry): BodyEntry {
  return partial;
}

/** Dwarf planets, asteroids, comets, regions, and extra moons added after v0.14. */
export const EXTRA_CATALOG: BodyEntry[] = [
  body({
    id: "eris",
    name: "Eris",
    type: "dwarf-planet",
    parentId: "sun",
    au: 67.8,
    longitudeDeg: 120,
    displaySize: 12,
    color: "#c8ccd4",
  }),
  body({
    id: "haumea",
    name: "Haumea",
    type: "dwarf-planet",
    parentId: "sun",
    au: 43.1,
    longitudeDeg: 88,
    displaySize: 11,
    color: "#e8e4dc",
  }),
  body({
    id: "makemake",
    name: "Makemake",
    type: "dwarf-planet",
    parentId: "sun",
    au: 45.8,
    longitudeDeg: 176,
    displaySize: 11,
    color: "#c8a888",
  }),
  body({
    id: "sedna",
    name: "Sedna",
    type: "dwarf-planet",
    parentId: "sun",
    au: 76,
    longitudeDeg: 44,
    displaySize: 10,
    color: "#c98878",
    hardOnly: true,
  }),
  body({
    id: "quaoar",
    name: "Quaoar",
    type: "dwarf-planet",
    parentId: "sun",
    au: 43.4,
    longitudeDeg: 260,
    displaySize: 10,
    color: "#a87868",
    hardOnly: true,
  }),
  body({
    id: "orcus",
    name: "Orcus",
    type: "dwarf-planet",
    parentId: "sun",
    au: 39.2,
    longitudeDeg: 132,
    displaySize: 10,
    color: "#989898",
    hardOnly: true,
  }),
  body({
    id: "gonggong",
    name: "Gonggong",
    type: "dwarf-planet",
    parentId: "sun",
    au: 67.5,
    longitudeDeg: 200,
    displaySize: 10,
    color: "#b87878",
    hardOnly: true,
  }),
  body({
    id: "varuna",
    name: "Varuna",
    type: "dwarf-planet",
    parentId: "sun",
    au: 43.3,
    longitudeDeg: 16,
    displaySize: 9,
    color: "#887868",
    hardOnly: true,
  }),
  body({
    id: "ixion",
    name: "Ixion",
    type: "dwarf-planet",
    parentId: "sun",
    au: 39.3,
    longitudeDeg: 304,
    displaySize: 9,
    color: "#907868",
    hardOnly: true,
  }),
  body({
    id: "hygiea",
    name: "Hygiea",
    type: "dwarf-planet",
    parentId: "sun",
    au: 3.14,
    longitudeDeg: 192,
    displaySize: 9,
    color: "#a8a098",
    hardOnly: true,
  }),
  body({
    id: "vesta",
    name: "Vesta",
    type: "asteroid",
    parentId: "sun",
    au: 2.36,
    longitudeDeg: 64,
    displaySize: 10,
    color: "#d8d0c0",
  }),
  body({
    id: "pallas",
    name: "Pallas",
    type: "asteroid",
    parentId: "sun",
    au: 2.77,
    longitudeDeg: 228,
    displaySize: 9,
    color: "#b8b0a8",
  }),
  body({
    id: "psyche",
    name: "Psyche",
    type: "asteroid",
    parentId: "sun",
    au: 2.92,
    longitudeDeg: 148,
    displaySize: 10,
    color: "#c8a878",
  }),
  body({
    id: "bennu",
    name: "Bennu",
    type: "asteroid",
    parentId: "sun",
    au: 1.13,
    longitudeDeg: 276,
    displaySize: 8,
    color: "#a89888",
  }),
  body({
    id: "ryugu",
    name: "Ryugu",
    type: "asteroid",
    parentId: "sun",
    au: 1.19,
    longitudeDeg: 36,
    displaySize: 8,
    color: "#908070",
  }),
  body({
    id: "ida",
    name: "Ida",
    type: "asteroid",
    parentId: "sun",
    au: 2.86,
    longitudeDeg: 316,
    displaySize: 9,
    color: "#a89080",
  }),
  body({
    id: "gaspra",
    name: "Gaspra",
    type: "asteroid",
    parentId: "sun",
    au: 2.21,
    longitudeDeg: 172,
    displaySize: 8,
    color: "#989088",
    hardOnly: true,
  }),
  body({
    id: "mathilde",
    name: "Mathilde",
    type: "asteroid",
    parentId: "sun",
    au: 2.65,
    longitudeDeg: 92,
    displaySize: 8,
    color: "#686058",
    hardOnly: true,
  }),
  body({
    id: "eros",
    name: "Eros",
    type: "asteroid",
    parentId: "sun",
    au: 1.46,
    longitudeDeg: 248,
    displaySize: 8,
    color: "#b0a090",
    hardOnly: true,
  }),
  body({
    id: "itokawa",
    name: "Itokawa",
    type: "asteroid",
    parentId: "sun",
    au: 1.32,
    longitudeDeg: 112,
    displaySize: 7,
    color: "#a89888",
    hardOnly: true,
  }),
  body({
    id: "lutetia",
    name: "Lutetia",
    type: "asteroid",
    parentId: "sun",
    au: 2.79,
    longitudeDeg: 52,
    displaySize: 8,
    color: "#908880",
    hardOnly: true,
  }),
  body({
    id: "halley",
    name: "Halley's Comet",
    type: "comet",
    parentId: "sun",
    au: 0.59,
    longitudeDeg: 184,
    displaySize: 9,
    color: "#c8e8ff",
  }),
  body({
    id: "hale-bopp",
    name: "Hale-Bopp",
    type: "comet",
    parentId: "sun",
    au: 0.91,
    longitudeDeg: 268,
    displaySize: 10,
    color: "#d0f0ff",
  }),
  body({
    id: "67p",
    name: "67P/Churyumov-Gerasimenko",
    type: "comet",
    parentId: "sun",
    au: 1.24,
    longitudeDeg: 72,
    displaySize: 9,
    color: "#b8d8e8",
  }),
  body({
    id: "tempel-1",
    name: "Tempel 1",
    type: "comet",
    parentId: "sun",
    au: 1.5,
    longitudeDeg: 332,
    displaySize: 8,
    color: "#c0dce8",
  }),
  body({
    id: "wild-2",
    name: "Wild 2",
    type: "comet",
    parentId: "sun",
    au: 1.59,
    longitudeDeg: 156,
    displaySize: 8,
    color: "#b8d0e0",
  }),
  body({
    id: "shoemaker-levy-9",
    name: "Shoemaker-Levy 9",
    type: "comet",
    parentId: "sun",
    au: 5.2,
    longitudeDeg: 24,
    displaySize: 8,
    color: "#a8c8d8",
  }),
  body({
    id: "scattered-disc",
    name: "Scattered Disc",
    type: "region",
    parentId: "sun",
    innerAu: 62,
    au: 78,
    longitudeDeg: 0,
    displaySize: 0,
    color: "#6a7a9a",
  }),
  body({
    id: "heliosphere",
    name: "Heliosphere",
    type: "region",
    parentId: "sun",
    innerAu: 78,
    au: 95,
    longitudeDeg: 0,
    displaySize: 0,
    color: "#4a5570",
  }),
  body({
    id: "jupiter-trojans",
    name: "Jupiter Trojans",
    type: "region",
    parentId: "sun",
    innerAu: 4.95,
    au: 5.45,
    longitudeDeg: 0,
    displaySize: 0,
    color: "#a89070",
  }),
  body({
    id: "neptune-trojans",
    name: "Neptune Trojans",
    type: "region",
    parentId: "sun",
    innerAu: 29.7,
    au: 30.4,
    longitudeDeg: 0,
    displaySize: 0,
    color: "#6888a8",
  }),
  body({
    id: "charon",
    name: "Charon",
    type: "moon",
    parentId: "pluto",
    au: 0,
    localOrbit: 22,
    longitudeDeg: 180,
    displaySize: 11,
    color: "#b8b0a8",
    hardOnly: true,
  }),
  body({
    id: "nix",
    name: "Nix",
    type: "moon",
    parentId: "pluto",
    au: 0,
    localOrbit: 34,
    longitudeDeg: 40,
    displaySize: 6,
    color: "#a8a098",
    hardOnly: true,
  }),
  body({
    id: "hydra",
    name: "Hydra",
    type: "moon",
    parentId: "pluto",
    au: 0,
    localOrbit: 40,
    longitudeDeg: 120,
    displaySize: 6,
    color: "#989088",
    hardOnly: true,
  }),
  body({
    id: "kerberos",
    name: "Kerberos",
    type: "moon",
    parentId: "pluto",
    au: 0,
    localOrbit: 36,
    longitudeDeg: 200,
    displaySize: 5,
    color: "#908880",
    hardOnly: true,
  }),
  body({
    id: "styx",
    name: "Styx",
    type: "moon",
    parentId: "pluto",
    au: 0,
    localOrbit: 30,
    longitudeDeg: 280,
    displaySize: 5,
    color: "#888078",
    hardOnly: true,
  }),
  body({
    id: "amalthea",
    name: "Amalthea",
    type: "moon",
    parentId: "jupiter",
    au: 0,
    localOrbit: 78,
    longitudeDeg: 50,
    displaySize: 8,
    color: "#c87858",
    hardOnly: true,
  }),
  body({
    id: "hyperion",
    name: "Hyperion",
    type: "moon",
    parentId: "saturn",
    au: 0,
    localOrbit: 176,
    longitudeDeg: 88,
    displaySize: 8,
    color: "#c8b898",
    hardOnly: true,
  }),
  body({
    id: "phoebe",
    name: "Phoebe",
    type: "moon",
    parentId: "saturn",
    au: 0,
    localOrbit: 204,
    longitudeDeg: 240,
    displaySize: 8,
    color: "#686058",
    hardOnly: true,
  }),
  body({
    id: "puck",
    name: "Puck",
    type: "moon",
    parentId: "uranus",
    au: 0,
    localOrbit: 40,
    longitudeDeg: 60,
    displaySize: 7,
    color: "#b8c0c8",
    hardOnly: true,
  }),
  body({
    id: "proteus",
    name: "Proteus",
    type: "moon",
    parentId: "neptune",
    au: 0,
    localOrbit: 44,
    longitudeDeg: 20,
    displaySize: 9,
    color: "#787068",
    hardOnly: true,
  }),
  body({
    id: "nereid",
    name: "Nereid",
    type: "moon",
    parentId: "neptune",
    au: 0,
    localOrbit: 76,
    longitudeDeg: 200,
    displaySize: 8,
    color: "#909088",
    hardOnly: true,
  }),
  body({
    id: "dysnomia",
    name: "Dysnomia",
    type: "moon",
    parentId: "eris",
    au: 0,
    localOrbit: 26,
    longitudeDeg: 90,
    displaySize: 6,
    color: "#989898",
    hardOnly: true,
  }),
  body({
    id: "hiiaka",
    name: "Hi'iaka",
    type: "moon",
    parentId: "haumea",
    au: 0,
    localOrbit: 20,
    longitudeDeg: 140,
    displaySize: 6,
    color: "#d0c8c0",
    hardOnly: true,
  }),
  body({
    id: "namaka",
    name: "Namaka",
    type: "moon",
    parentId: "haumea",
    au: 0,
    localOrbit: 16,
    longitudeDeg: 300,
    displaySize: 5,
    color: "#c0b8b0",
    hardOnly: true,
  }),
  body({
    id: "mk2",
    name: "MK 2",
    type: "moon",
    parentId: "makemake",
    au: 0,
    localOrbit: 18,
    longitudeDeg: 220,
    displaySize: 5,
    color: "#808080",
    hardOnly: true,
  }),
];
