export type SpacecraftGroup = "inner" | "earth" | "mars" | "giants" | "outer";

export type SpacecraftEntry = {
  id: string;
  name: string;
  type: "spacecraft";
  parentId: string;
  au: number;
  localOrbit?: number;
  longitudeDeg: number;
  displaySize: number;
  color: string;
  spacecraftGroup: SpacecraftGroup;
};

function craft(partial: SpacecraftEntry): SpacecraftEntry {
  return partial;
}

/**
 * Famous probes and satellites still in the Solar System (or coasting
 * beyond it). Earth has thousands of satellites; this set is the ones
 * players can reasonably learn on the map.
 */
export const SPACECRAFT_CATALOG: SpacecraftEntry[] = [
  craft({
    id: "parker-solar-probe",
    name: "Parker Solar Probe",
    type: "spacecraft",
    parentId: "sun",
    au: 0.12,
    longitudeDeg: 18,
    displaySize: 11,
    color: "#f4c44a",
    spacecraftGroup: "inner",
  }),
  craft({
    id: "solar-orbiter",
    name: "Solar Orbiter",
    type: "spacecraft",
    parentId: "sun",
    au: 0.45,
    longitudeDeg: 204,
    displaySize: 11,
    color: "#e8b060",
    spacecraftGroup: "inner",
  }),
  craft({
    id: "bepicolombo",
    name: "BepiColombo",
    type: "spacecraft",
    parentId: "mercury",
    au: 0,
    localOrbit: 38,
    longitudeDeg: 70,
    displaySize: 11,
    color: "#c8b090",
    spacecraftGroup: "inner",
  }),
  craft({
    id: "akatsuki",
    name: "Akatsuki",
    type: "spacecraft",
    parentId: "venus",
    au: 0,
    localOrbit: 48,
    longitudeDeg: 118,
    displaySize: 11,
    color: "#f0c070",
    spacecraftGroup: "inner",
  }),
  craft({
    id: "iss",
    name: "ISS",
    type: "spacecraft",
    parentId: "earth",
    au: 0,
    localOrbit: 52,
    longitudeDeg: 12,
    displaySize: 12,
    color: "#d8e4f0",
    spacecraftGroup: "earth",
  }),
  craft({
    id: "hubble",
    name: "Hubble",
    type: "spacecraft",
    parentId: "earth",
    au: 0,
    localOrbit: 64,
    longitudeDeg: 88,
    displaySize: 11,
    color: "#90b8e8",
    spacecraftGroup: "earth",
  }),
  craft({
    id: "jwst",
    name: "James Webb Space Telescope",
    type: "spacecraft",
    parentId: "earth",
    au: 0,
    localOrbit: 80,
    longitudeDeg: 168,
    displaySize: 12,
    color: "#c8d8e8",
    spacecraftGroup: "earth",
  }),
  craft({
    id: "chandra",
    name: "Chandra",
    type: "spacecraft",
    parentId: "earth",
    au: 0,
    localOrbit: 96,
    longitudeDeg: 248,
    displaySize: 10,
    color: "#a0b0c8",
    spacecraftGroup: "earth",
  }),
  craft({
    id: "mro",
    name: "Mars Reconnaissance Orbiter",
    type: "spacecraft",
    parentId: "mars",
    au: 0,
    localOrbit: 42,
    longitudeDeg: 30,
    displaySize: 11,
    color: "#ff8a5c",
    spacecraftGroup: "mars",
  }),
  craft({
    id: "maven",
    name: "MAVEN",
    type: "spacecraft",
    parentId: "mars",
    au: 0,
    localOrbit: 52,
    longitudeDeg: 110,
    displaySize: 11,
    color: "#e07048",
    spacecraftGroup: "mars",
  }),
  craft({
    id: "hope",
    name: "Hope",
    type: "spacecraft",
    parentId: "mars",
    au: 0,
    localOrbit: 62,
    longitudeDeg: 198,
    displaySize: 11,
    color: "#d4a060",
    spacecraftGroup: "mars",
  }),
  craft({
    id: "mars-odyssey",
    name: "Mars Odyssey",
    type: "spacecraft",
    parentId: "mars",
    au: 0,
    localOrbit: 72,
    longitudeDeg: 268,
    displaySize: 10,
    color: "#c06040",
    spacecraftGroup: "mars",
  }),
  craft({
    id: "mars-express",
    name: "Mars Express",
    type: "spacecraft",
    parentId: "mars",
    au: 0,
    localOrbit: 82,
    longitudeDeg: 328,
    displaySize: 10,
    color: "#b05038",
    spacecraftGroup: "mars",
  }),
  craft({
    id: "tianwen-1",
    name: "Tianwen-1",
    type: "spacecraft",
    parentId: "mars",
    au: 0,
    localOrbit: 92,
    longitudeDeg: 48,
    displaySize: 10,
    color: "#e87850",
    spacecraftGroup: "mars",
  }),
  craft({
    id: "juno",
    name: "Juno",
    type: "spacecraft",
    parentId: "jupiter",
    au: 0,
    localOrbit: 72,
    longitudeDeg: 42,
    displaySize: 12,
    color: "#e8c070",
    spacecraftGroup: "giants",
  }),
  craft({
    id: "juice",
    name: "JUICE",
    type: "spacecraft",
    parentId: "sun",
    au: 3.4,
    longitudeDeg: 248,
    displaySize: 11,
    color: "#c8b888",
    spacecraftGroup: "giants",
  }),
  craft({
    id: "europa-clipper",
    name: "Europa Clipper",
    type: "spacecraft",
    parentId: "sun",
    au: 2.15,
    longitudeDeg: 312,
    displaySize: 11,
    color: "#b8c8d8",
    spacecraftGroup: "giants",
  }),
  craft({
    id: "galileo-spacecraft",
    name: "Galileo",
    type: "spacecraft",
    parentId: "jupiter",
    au: 0,
    localOrbit: 58,
    longitudeDeg: 210,
    displaySize: 10,
    color: "#d0b070",
    spacecraftGroup: "giants",
  }),
  craft({
    id: "cassini",
    name: "Cassini",
    type: "spacecraft",
    parentId: "saturn",
    au: 0,
    localOrbit: 68,
    longitudeDeg: 96,
    displaySize: 11,
    color: "#f0d48a",
    spacecraftGroup: "giants",
  }),
  craft({
    id: "new-horizons",
    name: "New Horizons",
    type: "spacecraft",
    parentId: "sun",
    au: 61,
    longitudeDeg: 292,
    displaySize: 12,
    color: "#8ec8ff",
    spacecraftGroup: "outer",
  }),
  craft({
    id: "voyager-2",
    name: "Voyager 2",
    type: "spacecraft",
    parentId: "sun",
    au: 139,
    longitudeDeg: 318,
    displaySize: 13,
    color: "#f0c060",
    spacecraftGroup: "outer",
  }),
  craft({
    id: "voyager-1",
    name: "Voyager 1",
    type: "spacecraft",
    parentId: "sun",
    au: 166,
    longitudeDeg: 253,
    displaySize: 13,
    color: "#ffd36a",
    spacecraftGroup: "outer",
  }),
  craft({
    id: "pioneer-10",
    name: "Pioneer 10",
    type: "spacecraft",
    parentId: "sun",
    au: 137,
    longitudeDeg: 64,
    displaySize: 11,
    color: "#d0a050",
    spacecraftGroup: "outer",
  }),
  craft({
    id: "pioneer-11",
    name: "Pioneer 11",
    type: "spacecraft",
    parentId: "sun",
    au: 115,
    longitudeDeg: 22,
    displaySize: 11,
    color: "#c89848",
    spacecraftGroup: "outer",
  }),
  craft({
    id: "ulysses",
    name: "Ulysses",
    type: "spacecraft",
    parentId: "sun",
    au: 5.4,
    longitudeDeg: 140,
    displaySize: 10,
    color: "#a8b8c8",
    spacecraftGroup: "outer",
  }),
  craft({
    id: "lucy",
    name: "Lucy",
    type: "spacecraft",
    parentId: "sun",
    au: 2.8,
    longitudeDeg: 176,
    displaySize: 10,
    color: "#e0c898",
    spacecraftGroup: "outer",
  }),
  craft({
    id: "psyche-probe",
    name: "Psyche",
    type: "spacecraft",
    parentId: "sun",
    au: 2.4,
    longitudeDeg: 88,
    displaySize: 10,
    color: "#d8b878",
    spacecraftGroup: "outer",
  }),
];
